name: Build and Package

on: [push, pull_request]

jobs:
    build-macos-x86_64:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Clean previous builds
              run: rm -rf dist build

            - name: Build Intel executable
              run: |
                  arch -x86_64 python -m PyInstaller app.spec
              env:
                  ARCHFLAGS: "-arch x86_64"

            - name: Upload macOS x86_64 artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-macos-x86_64
                  path: dist/app.app

    build-macos-arm64:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Clean previous builds
              run: rm -rf dist build

            - name: Build ARM executable
              run: |
                  arch -arm64 python -m PyInstaller app.spec
              env:
                  ARCHFLAGS: "-arch arm64"

            - name: Upload macOS arm64 artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-macos-arm64
                  path: dist/app.app

    build-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build Ubuntu executable
              run: pyinstaller app.spec

            - name: Upload Ubuntu artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-ubuntu
                  path: dist/app

    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v4

            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build Windows executable
              run: pyinstaller app.spec

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v4
              with:
                  name: app-windows
                  path: dist/app.exe
