name: Build and Package

on: [push, pull_request]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build Intel executable
              run: |
                  arch -x86_64 python -m PyInstaller --onefile --windowed app.py
              env:
                  ARCHFLAGS: "-arch x86_64"

            - name: Build ARM executable
              run: |
                  arch -arm64 python -m PyInstaller --onefile --windowed app.py
              env:
                  ARCHFLAGS: "-arch arm64"

            - name: Combine executables
              run: |
                  mkdir -p dist/universal
                  lipo -create -output dist/universal/app dist/app dist/app_arm64

            - name: Upload macOS artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-macos
                  path: dist/universal/app

    build-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build Ubuntu executable
              run: pyinstaller --onefile --windowed app.py

            - name: Upload Ubuntu artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-ubuntu
                  path: dist/app

    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build Windows executable
              run: pyinstaller --onefile --windowed app.py

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-windows
                  path: dist/app.exe
