name: Build and Package

on: [push, pull_request]

jobs:
    build-macos:
        runs-on: macos-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build macOS executable
              run: pyinstaller --onefile --windowed app.py

            - name: Upload macOS artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-macos
                  path: dist/app

    build-ubuntu:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build Ubuntu executable
              run: pyinstaller --onefile app.py

            - name: Upload Ubuntu artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-ubuntu
                  path: dist/app

    build-windows:
        runs-on: windows-latest
        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Install dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install pyinstaller PyQt6

            - name: Build Windows executable
              run: pyinstaller --onefile app.py

            - name: Upload Windows artifact
              uses: actions/upload-artifact@v2
              with:
                  name: app-windows
                  path: dist/app.exe
